# basic options
title: md.lib.ru
author: PWRMind
email: your-email@domain.com
description: A wonderful site
twitter_username: jekyllrb
github_username:  pwrmind
lang: ru

# Build settings
markdown: kramdown
#permalink: pretty
# theme: minima
collections:
  books:
    output: true
    permalink: none